//
//  TrebleClefVisualizationMappings.swift
//  FrenchHornApp
//
//  Created by Lorenzo Brown on 8/30/22.
//

import Foundation


let trebleClefNoteMappings: [Int : TrebleClefNoteVisualization] = [

	C0.id: TCC0,
	CSharp0.id : TCCSharp0,
	DFlat0.id: TCDFlat0,
	D0.id: TCD0,
	DSharp0.id: TCDSharp0,
	EFlat0.id: TCEFlat0,
	E0.id: TCE0,
	F0.id: TCF0,
	FSharp0.id :TCFSharp0,
	GFlat0.id: TCGFlat0,
	G0.id: TCG0,
	GSharp0.id : TCGSharp0,
	AFlat0.id: TCAFlat0,
	A0.id: TCAFlat0,
	ASharp0.id: TCAFlat0,
	BFlat0.id: TCBFlat0,
	B0.id: TCB0,

	C1.id: TCC1,
	CSharp1.id : TCCSharp1,
	DFlat1.id: TCDFlat1,
	D1.id: TCD1,
	DSharp1.id: TCDSharp1,
	EFlat1.id: TCEFlat1,
	E1.id: TCE1,
	F1.id: TCF1,
	FSharp1.id :TCFSharp1,
	GFlat1.id: TCGFlat1,
	G1.id: TCG1,
	GSharp1.id : TCGSharp1,
	AFlat1.id: TCAFlat1,
	A1.id: TCAFlat1,
	ASharp1.id: TCAFlat1,
	BFlat1.id: TCBFlat1,
	B1.id: TCB1,

	C2.id: TCC2,
	CSharp2.id : TCCSharp2,
	DFlat2.id: TCDFlat2,
	D2.id: TCD2,
	DSharp2.id: TCDSharp2,
	EFlat2.id: TCEFlat2,
	E2.id: TCE2,
	F2.id: TCF2,
	FSharp2.id :TCFSharp2,
	GFlat2.id: TCGFlat2,
	G2.id: TCG2,
	GSharp2.id : TCGSharp2,
	AFlat2.id: TCAFlat2,
	A2.id: TCAFlat2,
	ASharp2.id: TCAFlat2,
	BFlat2.id: TCBFlat2,
	B2.id: TCB2,

	C3.id: TCC3,
	CSharp3.id : TCCSharp3,
	DFlat3.id: TCDFlat3,
	D3.id: TCD3,
	DSharp3.id: TCDSharp3,
	EFlat3.id: TCEFlat3,
	E3.id: TCE3,
	F3.id: TCF3,
	FSharp3.id :TCFSharp3,
	GFlat3.id: TCGFlat3,
	G3.id: TCG3,
	GSharp3.id : TCGSharp3,
	AFlat3.id: TCAFlat3,
	A3.id: TCAFlat3,
	ASharp3.id: TCAFlat3,
	BFlat3.id: TCBFlat3,
	B3.id: TCB3,


	C4.id: TCC4,
	CSharp4.id : TCCSharp4,
	DFlat4.id: TCDFlat4,
	D4.id: TCD4,
	DSharp4.id: TCDSharp4,
	EFlat4.id: TCEFlat4,
	E4.id: TCE4,
	F4.id: TCF4,
	FSharp4.id :TCFSharp4,
	GFlat4.id: TCGFlat4,
	G4.id: TCG4,
	GSharp4.id : TCGSharp4,
	AFlat4.id: TCAFlat4,
	A4.id: TCAFlat4,
	ASharp4.id: TCAFlat4,
	BFlat4.id: TCBFlat4,
	B4.id: TCB4,


	C5.id: TCC5,
	CSharp5.id : TCCSharp5,
	DFlat5.id: TCDFlat5,
	D5.id: TCD5,
	DSharp5.id: TCDSharp5,
	EFlat5.id: TCEFlat5,
	E5.id: TCE5,
	F5.id: TCF5,
	FSharp5.id :TCFSharp5,
	GFlat5.id: TCGFlat5,
	G5.id: TCG5,
	GSharp5.id : TCGSharp5,
	AFlat5.id: TCAFlat5,
	A5.id: TCAFlat5,
	ASharp5.id: TCAFlat5,
	BFlat5.id: TCBFlat5,
	B5.id: TCB5,


	C6.id: TCC6,
	CSharp6.id : TCCSharp6,
	DFlat6.id: TCDFlat6,
	D6.id: TCD6,
	DSharp6.id: TCDSharp6,
	EFlat6.id: TCEFlat6,
	E6.id: TCE6,
	F6.id: TCF6,
	FSharp6.id :TCFSharp6,
	GFlat6.id: TCGFlat6,
	G6.id: TCG6,
	GSharp6.id : TCGSharp6,
	AFlat6.id: TCAFlat6,
	A6.id: TCAFlat6,
	ASharp6.id: TCAFlat6,
	BFlat6.id: TCBFlat6,
	B6.id: TCB6,


	C7.id: TCC7,
	CSharp7.id : TCCSharp7,
	DFlat7.id: TCDFlat7,
	D7.id: TCD7,
	DSharp7.id: TCDSharp7,
	EFlat7.id: TCEFlat7,
	E7.id: TCE7,
	F7.id: TCF7,
	FSharp7.id :TCFSharp7,
	GFlat7.id: TCGFlat7,
	G7.id: TCG7,
	GSharp7.id : TCGSharp7,
	AFlat7.id: TCAFlat7,
	A7.id: TCAFlat7,
	ASharp7.id: TCAFlat7,
	BFlat7.id: TCBFlat7,
	B7.id: TCB7,


	C8.id: TCC8,
	CSharp8.id : TCCSharp8,
	DFlat8.id: TCDFlat8,
	D8.id: TCD8,
	DSharp8.id: TCDSharp8,
	EFlat8.id: TCEFlat8,
	E8.id: TCE8,
	F8.id: TCF8,
	FSharp8.id :TCFSharp8,
	GFlat8.id: TCGFlat8,
	G8.id: TCG8,
	GSharp8.id : TCGSharp8,
	AFlat8.id: TCAFlat8,
	A8.id: TCAFlat8,
	ASharp8.id: TCAFlat8,
	BFlat8.id: TCBFlat8,

]
