//
//  TrebleClefNoteVisualizations.swift
//  FrenchHornApp
//
//  Created by Lorenzo Brown on 8/30/22.
//

import Foundation
import SwiftUI

let TCC0 = TrebleClefNoteVisualization(stepsFromMidpoint: -20, ledgerLines: Array(downledgers[0...7]),  incidental: .natural)
let TCCSharp0 = TrebleClefNoteVisualization(stepsFromMidpoint: -20, ledgerLines: Array(downledgers[0...7]), incidental: .sharp)
let TCDFlat0 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]),  incidental: .flat)
let TCD0 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]), incidental: .natural)
let TCDSharp0 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]),  incidental: .sharp)
let TCEFlat0 = TrebleClefNoteVisualization(stepsFromMidpoint: -18, ledgerLines: Array(downledgers[0...6]), incidental: .flat)
let TCE0 = TrebleClefNoteVisualization(stepsFromMidpoint: -18, ledgerLines: Array(downledgers[0...6]),  incidental: .natural)
let TCF0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -17, ledgerLines: Array(downledgers[0...5]), incidental: .natural)
let TCFSharp0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -17,ledgerLines: Array(downledgers[0...5]),  incidental: .sharp)
let TCGFlat0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]), incidental: .flat)
let TCG0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]),  incidental: .natural)
let TCGSharp0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]), incidental: .sharp)
let TCAFlat0 = TrebleClefNoteVisualization(stepsFromMidpoint: -15, ledgerLines: Array(downledgers[0...4]),  incidental: .flat)
let TCA0 = TrebleClefNoteVisualization(stepsFromMidpoint: -15,  ledgerLines: Array(downledgers[0...4]), incidental: .natural)
let TCASharp0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -15, ledgerLines: Array(downledgers[0...4]), incidental: .sharp)
let TCBFlat0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -14, ledgerLines: Array(downledgers[0...4]), incidental: .flat)
let TCB0 =  TrebleClefNoteVisualization(stepsFromMidpoint: -14, ledgerLines: Array(downledgers[0...4]), incidental: .natural)
let TCC1 = TrebleClefNoteVisualization(stepsFromMidpoint: -20, ledgerLines: Array(downledgers[0...7]),  incidental: .natural)
let TCCSharp1 = TrebleClefNoteVisualization(stepsFromMidpoint: -20, ledgerLines: Array(downledgers[0...7]), incidental: .sharp)
let TCDFlat1 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]),  incidental: .flat)
let TCD1 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]), incidental: .natural)
let TCDSharp1 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]),  incidental: .sharp)
let TCEFlat1 = TrebleClefNoteVisualization(stepsFromMidpoint: -18, ledgerLines: Array(downledgers[0...6]), incidental: .flat)
let TCE1 = TrebleClefNoteVisualization(stepsFromMidpoint: -18, ledgerLines: Array(downledgers[0...6]),  incidental: .natural)
let TCF1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -17, ledgerLines: Array(downledgers[0...5]), incidental: .natural)
let TCFSharp1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -17,ledgerLines: Array(downledgers[0...5]),  incidental: .sharp)
let TCGFlat1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]), incidental: .flat)
let TCG1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]),  incidental: .natural)
let TCGSharp1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]), incidental: .sharp)
let TCAFlat1 = TrebleClefNoteVisualization(stepsFromMidpoint: -15, ledgerLines: Array(downledgers[0...4]),  incidental: .flat)
let TCA1 = TrebleClefNoteVisualization(stepsFromMidpoint: -15,  ledgerLines: Array(downledgers[0...4]), incidental: .natural)
let TCASharp1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -15, ledgerLines: Array(downledgers[0...4]), incidental: .sharp)
let TCBFlat1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -14, ledgerLines: Array(downledgers[0...4]), incidental: .flat)
let TCB1 =  TrebleClefNoteVisualization(stepsFromMidpoint: -14, ledgerLines: Array(downledgers[0...4]), incidental: .natural)

let TCC2 = TrebleClefNoteVisualization(stepsFromMidpoint: -20, ledgerLines: Array(downledgers[0...7]),  incidental: .natural)
let TCCSharp2 = TrebleClefNoteVisualization(stepsFromMidpoint: -20, ledgerLines: Array(downledgers[0...7]), incidental: .sharp)
let TCDFlat2 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]),  incidental: .flat)
let TCD2 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]), incidental: .natural)
let TCDSharp2 = TrebleClefNoteVisualization(stepsFromMidpoint: -19, ledgerLines: Array(downledgers[0...6]),  incidental: .sharp)
let TCEFlat2 = TrebleClefNoteVisualization(stepsFromMidpoint: -18, ledgerLines: Array(downledgers[0...6]), incidental: .flat)
let TCE2 = TrebleClefNoteVisualization(stepsFromMidpoint: -18, ledgerLines: Array(downledgers[0...6]),  incidental: .natural)
let TCF2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -17, ledgerLines: Array(downledgers[0...5]), incidental: .natural)
let TCFSharp2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -17,ledgerLines: Array(downledgers[0...5]),  incidental: .sharp)
let TCGFlat2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]), incidental: .flat)
let TCG2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]),  incidental: .natural)
let TCGSharp2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -16, ledgerLines: Array(downledgers[0...5]), incidental: .sharp)
let TCAFlat2 = TrebleClefNoteVisualization(stepsFromMidpoint: -15, ledgerLines: Array(downledgers[0...4]),  incidental: .flat)
let TCA2 = TrebleClefNoteVisualization(stepsFromMidpoint: -15,  ledgerLines: Array(downledgers[0...4]), incidental: .natural)
let TCASharp2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -15, ledgerLines: Array(downledgers[0...4]), incidental: .sharp)
let TCBFlat2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -14, ledgerLines: Array(downledgers[0...4]), incidental: .flat)
let TCB2 =  TrebleClefNoteVisualization(stepsFromMidpoint: -14, ledgerLines: Array(downledgers[0...4]), incidental: .natural)

let TCC3 = TrebleClefNoteVisualization(stepsFromMidpoint: -13, ledgerLines: Array(downledgers[0...3]), incidental: .natural)
let TCCSharp3 = TrebleClefNoteVisualization(stepsFromMidpoint: -13, ledgerLines: Array(downledgers[0...3]), incidental: .sharp)
let TCDFlat3 = TrebleClefNoteVisualization(stepsFromMidpoint: -12, ledgerLines: Array(downledgers[0...3]), incidental: .flat)
let TCD3 = TrebleClefNoteVisualization(stepsFromMidpoint: -12, ledgerLines: Array(downledgers[0...3]), incidental: .natural)
let TCDSharp3 = TrebleClefNoteVisualization(stepsFromMidpoint: -12, ledgerLines: Array(downledgers[0...3]), incidental: .sharp)
let TCEFlat3 = TrebleClefNoteVisualization(stepsFromMidpoint: -11, ledgerLines: Array(downledgers[0...2]), incidental: .flat)
let TCE3 = TrebleClefNoteVisualization(stepsFromMidpoint: -11, ledgerLines: Array(downledgers[0...2]), incidental: .natural)
let TCF3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -10, ledgerLines: Array(downledgers[0...2]), incidental: .natural)
let TCFSharp3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -10, ledgerLines: Array(downledgers[0...2]), incidental: .sharp)
let TCGFlat3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -9, ledgerLines: Array(downledgers[0...1]), incidental: .flat)
let TCG3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -9, ledgerLines: Array(downledgers[0...1]), incidental: .natural)
let TCGSharp3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -9, ledgerLines: Array(downledgers[0...1]), incidental: .sharp)
let TCAFlat3 = TrebleClefNoteVisualization(stepsFromMidpoint: -8, ledgerLines: Array(downledgers[0...1]), incidental: .flat)
let TCA3 = TrebleClefNoteVisualization(stepsFromMidpoint: -8, ledgerLines: Array(downledgers[0...1]), incidental: .natural)
let TCASharp3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -8, ledgerLines: Array(downledgers[0...1]), incidental: .sharp)
let TCBFlat3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -7, ledgerLines: [downledgers[0]], incidental: .flat)
let TCB3 =  TrebleClefNoteVisualization(stepsFromMidpoint: -7, ledgerLines: [downledgers[0]], incidental: .natural)



let TCC4 = TrebleClefNoteVisualization(stepsFromMidpoint: -6,ledgerLines: [downledgers[0]], incidental: .natural)
let TCCSharp4 = TrebleClefNoteVisualization(stepsFromMidpoint: -6,ledgerLines: [downledgers[0]], incidental: .sharp)
let TCDFlat4 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .flat)
let TCD4 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .natural)
let TCDSharp4 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .sharp)
let TCEFlat4 = TrebleClefNoteVisualization(stepsFromMidpoint: -4, incidental: .flat)
let TCE4 = TrebleClefNoteVisualization(stepsFromMidpoint: -4, incidental: .natural)
let TCF4 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .natural)
let TCFSharp4 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .sharp)
let TCGFlat4 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .flat)
let TCG4 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .natural)
let TCGSharp4 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .sharp)
let TCAFlat4 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .flat)
let TCA4 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .natural)
let TCASharp4 =  TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .sharp)
let TCBFlat4 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .flat)
let TCB4 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .natural)

let TCC5 = TrebleClefNoteVisualization(stepsFromMidpoint: 1, incidental: .natural)
let TCCSharp5 = TrebleClefNoteVisualization(stepsFromMidpoint: 1, incidental: .sharp)
let TCDFlat5 = TrebleClefNoteVisualization(stepsFromMidpoint: 2, incidental: .flat)
let TCD5 = TrebleClefNoteVisualization(stepsFromMidpoint: 2, incidental: .natural)
let TCDSharp5 = TrebleClefNoteVisualization(stepsFromMidpoint: 2, incidental: .sharp)
let TCEFlat5 = TrebleClefNoteVisualization(stepsFromMidpoint: 3, incidental: .flat)
let TCE5 = TrebleClefNoteVisualization(stepsFromMidpoint: 3, incidental: .natural)
let TCF5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 4, incidental: .natural)
let TCFSharp5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 4, incidental: .sharp)
let TCGFlat5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 5, incidental: .flat)
let TCG5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 5, incidental: .natural)
let TCGSharp5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 5, incidental: .sharp)
let TCAFlat5 = TrebleClefNoteVisualization(stepsFromMidpoint: 6, ledgerLines: [upledgers[0]],  incidental: .flat)
let TCA5 = TrebleClefNoteVisualization(stepsFromMidpoint: 6, ledgerLines: [upledgers[0]], incidental: .natural)
let TCASharp5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 6, ledgerLines: [upledgers[0]],incidental: .sharp)
let TCBFlat5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 7, ledgerLines: [upledgers[0]], incidental: .flat)
let TCB5 =  TrebleClefNoteVisualization(stepsFromMidpoint: 7, ledgerLines: [upledgers[0]], incidental: .natural)

// TODO: Finish these placements 
let TCC6 = TrebleClefNoteVisualization(stepsFromMidpoint: 8, ledgerLines: Array(upledgers[0...1]), incidental: .natural)
let TCCSharp6 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .sharp)
let TCDFlat6 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .flat)
let TCD6 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .natural)
let TCDSharp6 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .sharp)
let TCEFlat6 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .flat)
let TCE6 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .natural)
let TCF6 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .natural)
let TCFSharp6 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .sharp)
let TCGFlat6 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .flat)
let TCG6 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .natural)
let TCGSharp6 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .sharp)
let TCAFlat6 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .flat)
let TCA6 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .natural)
let TCASharp6 =  TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .sharp)
let TCBFlat6 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .flat)
let TCB6 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .natural)

let TCC7 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .natural)
let TCCSharp7 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .sharp)
let TCDFlat7 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .flat)
let TCD7 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .natural)
let TCDSharp7 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .sharp)
let TCEFlat7 = TrebleClefNoteVisualization(stepsFromMidpoint: -7, incidental: .flat)
let TCE7 = TrebleClefNoteVisualization(stepsFromMidpoint: -7, incidental: .natural)
let TCF7 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .natural)
let TCFSharp7 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .sharp)
let TCGFlat7 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .flat)
let TCG7 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .natural)
let TCGSharp7 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .sharp)
let TCAFlat7 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .flat)
let TCA7 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .natural)
let TCASharp7 =  TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .sharp)
let TCBFlat7 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .flat)
let TCB7 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .natural)

let TCC8 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .natural)
let TCCSharp8 = TrebleClefNoteVisualization(stepsFromMidpoint: -6, incidental: .sharp)
let TCDFlat8 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .flat)
let TCD8 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .natural)
let TCDSharp8 = TrebleClefNoteVisualization(stepsFromMidpoint: -5, incidental: .sharp)
let TCEFlat8 = TrebleClefNoteVisualization(stepsFromMidpoint: -8, incidental: .flat)
let TCE8 = TrebleClefNoteVisualization(stepsFromMidpoint: -8, incidental: .natural)
let TCF8 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .natural)
let TCFSharp8 =  TrebleClefNoteVisualization(stepsFromMidpoint: -3, incidental: .sharp)
let TCGFlat8 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .flat)
let TCG8 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .natural)
let TCGSharp8 =  TrebleClefNoteVisualization(stepsFromMidpoint: -2, incidental: .sharp)
let TCAFlat8 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .flat)
let TCA8 = TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .natural)
let TCASharp8 =  TrebleClefNoteVisualization(stepsFromMidpoint: -1, incidental: .sharp)
let TCBFlat8 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .flat)
let TCB8 =  TrebleClefNoteVisualization(stepsFromMidpoint: 0, incidental: .natural)
